feat(PrefilledInput): Added new prefilled input component. Code clean…
tabetalt/kit pull request #63
Opened 2020-10-13 08:45 UTC by TanyaDolgopolova

…ing by lint command
<img width="950" alt="Screenshot 2020-10-13 at 11 40 52" src="https://user-images.githubusercontent.com/35150766/95837729-99db6c80-0d49-11eb-93b3-ae227e300fb0.png">

Close #53

2020-10-13 09:32 UTC, kvokov commented on src/components/Input/components/PrefilledInput.tsx
> +            sx={{ width: textWidth }}
I think we need to calculate input width based on text length, `width: auto` or somehow

2020-10-13 09:32 UTC, kvokov commented on src/components/Input/components/PrefilledInput.css
> +.prefilledInput {
let's use `sx`  or `css` from `theme-ui` instead of plain css

2020-10-13 09:49 UTC, kvokov commented on src/components/Input/components/PrefilledInput.tsx
> +            sx={{ width: textWidth }}
please check this example
https://stackoverflow.com/questions/22655493/how-can-i-style-individual-parts-of-an-input-placeholder

2020-10-13 10:21 UTC, cobraz requested changes

2020-10-13 10:21 UTC, cobraz commented on src/components/Input/components/PrefilledInput.tsx
> +          <input
This should be a `<Input/>` not `<input/>`. Then it will get default styles from Theme UI.
 
![Skjermbilde 2020-10-13 kl  12 18 39](https://user-images.githubusercontent.com/3726815/95848520-749d2d00-0d4e-11eb-885f-611284ce3e66.png)

2020-10-13 10:21 UTC, cobraz commented on src/components/Input/components/PrefilledInput.tsx
> +      {prefilledTextPosition === TextPosition.LEFT && (
Can we solve this with flex-direction instead of having a if-statement?

2020-10-13 10:49 UTC, TanyaDolgopolova commented on src/components/Input/components/PrefilledInput.tsx
> +          <input
I use `<input />` instead of Theme-UI ones, because a `<Input />` have its own styles, and for situation when we need to have "prefilled" text in the input - it would not needed. So for that, I use container with similar style with html input without any border styles

2020-10-13 10:50 UTC, TanyaDolgopolova commented on src/components/Input/components/PrefilledInput.tsx
> +      {prefilledTextPosition === TextPosition.LEFT && (
Yeah, I will change it

> Can we solve this with flex-direction instead of having a if-statement?

2020-10-15 07:58 UTC, kvokov approved these changes

2020-10-15 12:41 UTC, cobraz approved these changes

2020-10-15 12:41 UTC, cobraz commented on src/components/Input/components/PrefilledInput.tsx
> +        <input
Can we use `theme-ui`'s [`<Input />`](https://theme-ui.com/components/input) and add styling to `theme/` as a [variant](https://theme-ui.com/components/variants)?

2020-10-15 12:41 UTC, cobraz commented on src/components/Input/components/styles.ts
> +} as ThemeUIStyleObject;
I don't generally like to have separate style files like this. There might be much less css styling if you'd use `<Input/>` too. What do you think?

2020-10-15 12:42 UTC, cobraz requested changes
Didn't mean to clicked approve.

2020-10-15 13:46 UTC, cobraz approved these changes
LGTM! @AnneMatilde any feedback from you here?

2020-10-15 13:57 UTC, AnneMatilde commented
Looking good! 

But it seems that some of the text is cut off on the left side:
![image](https://user-images.githubusercontent.com/54155334/96138834-79a0de80-0efe-11eb-9749-e533393ea0de.png)
![image](https://user-images.githubusercontent.com/54155334/96138860-81608300-0efe-11eb-87be-28cf68248279.png)

And when the text is long the ".com" moves away from the text: 
![image](https://user-images.githubusercontent.com/54155334/96138982-a0f7ab80-0efe-11eb-922c-c9114d162426.png)

2020-10-16 12:05 UTC, kvokov commented
@TanyaDolgopolova please set `borderRadius: none` for input

2020-10-20 14:47 UTC, AnneMatilde commented
Hey @TanyaDolgopolova! I see that the cropping on the left is fixed, nice!
But now the ".com" is in the same position, and if the name is too long the text disappears to the left:

<img width="220" alt="Skjermbilde 2020-10-20 kl  16 42 31" src="https://user-images.githubusercontent.com/54155334/96602866-c0724800-12f3-11eb-8a41-2723d5156059.png">

I think it was working better before, when the ".com" followed the length of the store name 😊

2020-10-20 15:32 UTC, TanyaDolgopolova commented
> Hey @TanyaDolgopolova! I see that the cropping on the left is fixed, nice!
> But now the ".com" is in the same position, and if the name is too long the text disappears to the left:
> 
> <img alt="Skjermbilde 2020-10-20 kl 16 42 31" width="220" src="https://user-images.githubusercontent.com/54155334/96602866-c0724800-12f3-11eb-8a41-2723d5156059.png">
> 
> I think it was working better before, when the ".com" followed the length of the store name 😊

Hi, this need to be working. I will check it

2020-10-21 07:47 UTC, cobraz commented
@AnneMatilde can you review?

2020-10-21 07:51 UTC, AnneMatilde commented
Nice! Looks perfect now 😊

2020-10-23 18:50 UTC, AnneMatilde approved these changes

2020-10-23 18:50 UTC, merged