feat(FileUpload): WIP Added basic FileUpload component
tabetalt/kit pull request #64
Opened 2020-10-15 09:17 UTC by kvokov

2020-10-15 12:34 UTC, cobraz requested changes

2020-10-15 12:34 UTC, cobraz commented on src/components/Button/Button.stories.tsx
> +import { Button } from './Button';
Why this?

2020-10-15 12:34 UTC, cobraz commented on src/components/FileUpload/FileUpload.tsx
> +  const [errors, setErrors] = useState([] as string[]); // eslint-disable-line @typescript-eslint/no-unused-vars
Why are these not used?

2020-10-15 12:34 UTC, cobraz commented on src/components/FileUpload/FileUpload.tsx
> +          // @ts-ignore
Is there a way that we can not have this?

2020-10-15 12:34 UTC, cobraz commented on src/components/FileUpload/components/FileUploadPreview.tsx
> +// TODO: add remove button
add and remove? :D

2020-10-15 14:22 UTC, kvokov commented on src/components/Button/Button.stories.tsx
> +import { Button } from './Button';
I think it's better way, bc for now we just reexport Button from `theme-ui` there, but we may add some customization to it, and it'll be applied also everywhere Button is used
make sense?
But actually I need button with loading state there, so I'll change this

2020-10-15 14:23 UTC, kvokov commented on src/components/FileUpload/FileUpload.tsx
> +  const [errors, setErrors] = useState([] as string[]); // eslint-disable-line @typescript-eslint/no-unused-vars
yeah, it's in progress

2020-10-15 14:26 UTC, kvokov commented on src/components/FileUpload/components/FileUploadPreview.tsx
> +// TODO: add remove button
I mean that would be good to have "remove" icon showed on hover on uploaded image preview to remove it, no?

2020-10-23 18:39 UTC, cobraz commented
@TanyaDolgopolova Can you take over this branch?

2020-10-26 10:40 UTC, TanyaDolgopolova commented
> @TanyaDolgopolova Can you take over this branch?

Sure

2020-10-28 09:18 UTC, cobraz commented
@TanyaDolgopolova Let me know when you want me to review this again :)

2020-10-28 13:29 UTC, TanyaDolgopolova approved these changes

2020-10-28 13:31 UTC, TanyaDolgopolova approved these changes

2020-10-29 18:50 UTC, cobraz approved these changes

2020-10-29 18:50 UTC, merged