feat(CheckboxList): Added checkbox list component
tabetalt/kit pull request #65
Opened 2020-10-15 09:42 UTC by TanyaDolgopolova

Close #50

2020-10-15 12:09 UTC, cobraz requested changes

2020-10-15 12:09 UTC, cobraz commented on src/components/CheckboxList/CheckboxList.tsx
> +              id={option.id}
Shouldn't this have a `key` value?

2020-10-15 12:11 UTC, TanyaDolgopolova commented on src/components/CheckboxList/CheckboxList.tsx
> +              id={option.id}
You are right, I will change it

2020-10-15 13:33 UTC, cobraz approved these changes
LGTM 🎉

2020-10-15 14:15 UTC, kvokov commented on src/components/CheckboxList/CheckboxList.tsx
> +              key={option.id}
key should be specified for `<Label>` as root element there

2020-10-16 12:02 UTC, kvokov approved these changes

2020-10-20 20:58 UTC, merged